Support for metrics and some other small improvements (#9)
* Added .gitignore

* Use bitnami postgresql and redis charts.

* Added migration guide.

* Support for external PostgreSQL and Redis.

* Bitname style chart.

* More bitnami friendly.

* TLS config.

* Removed sequin-0.1.0.tgz

* Added .helmignore

* Removed index.yaml

* Added maintainers.

* Added sources.

* Enabled serviceBindings for redis by default.

* Correct secret

* Disabled redis authentication.

* SEQUIN_LOG_FORMAT=CONSOLE by default

* Use Kubernetes secret to store SECRET_KEY_BASE and VAULT_KEY.

* Better livenessProbe, readinessProbe and startupProbe.

* Revert to original README.md.

* Improved README.

* Cleanup.

* Added the ability to set custom YAML configuration for Sequin.

* Attempt to fix configmap.

* Attempt to fix configmap.

* Attempt to fix: client.go:144: 2025-05-22 01:52:51.798362 +0300 +03 m=+13.774934293 [debug] creating 21 resource(s)
       Error: INSTALLATION FAILED: 1 error occurred:
       	* Deployment.apps "sequin-stage" is invalid: spec.template.spec.containers[0].volumeMounts[1].name: Not found: "configuration"

* Temp ignore CONFIG_FILE_PATH

* Restore CONFIG_FILE_PATH

* initialDelaySeconds: 15

* Use values for SECRET_KEY_BASE and VAULT_KEY.

* Temporarily disable podSecurityContext and containerSecurityContext. It doesn't work at the moment:

Migrations complete
Applying config
Substituting environment variables in /sequin/etc/config.yaml
2025/05/21 23:18:50 Failed to open log file:open sequin.log: read-only file system

* Added Prometheus metrics support.

* Sync ingress config with latest Bitnami approach.

* Revert "Temporarily disable podSecurityContext and containerSecurityContext. It doesn't work at the moment:"

This reverts commit ac2d8091bdf665d8f34705b190f5725addfac8ca.

* Update dependencies.

* Ingress labels.

* Updated dependencies.